[package]
name = "bachelor_thesis"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["client", "server"]

[[bin]]
name = "client"
path = "/client/src/main.rs"

[[bin]]
name = "server"
path = "/server/src/main.rs"

#crate-type = ["rlib"]
