version: '3.8'
services:
  server:
    build: ./server
    container_name: server
    networks:
      - ethernet
    cap_add:
      - NET_ADMIN
    ports:
      - "4433:4433"

  client:
    build: ./client
    container_name: client
    volumes:
      - /Users/yechankim/RustroverProjects/bachelor_thesis/measurements/:/app/data
    networks:
      - ethernet
    cap_add:
      - NET_ADMIN
    ports:
      - "3344:3344"

networks:
  ethernet:
    driver: bridge